//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BandCApplicationsEntities1 : DbContext
    {
        public BandCApplicationsEntities1()
            : base("name=BandCApplicationsEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BoardMember> BoardMembers { get; set; }
        public virtual DbSet<M_BoardsandCommissions> M_BoardsandCommissions { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<Person_Applications> Person_Applications { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<UsersInRole> UsersInRoles { get; set; }
        public virtual DbSet<Voluntary_Survey> Voluntary_Survey { get; set; }
    }
}
