//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public int PersonKey { get; set; }
        public string EmailAddress { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string StreetAddress { get; set; }
        public string City { get; set; }
        public string ZipCode { get; set; }
        public string Occupation { get; set; }
        public string BusinessName { get; set; }
        public string BusinessStreetAddress { get; set; }
        public string BusinessCity { get; set; }
        public string BusinessZipCode { get; set; }
        public string HomeTelephone { get; set; }
        public string BusinessTelephone { get; set; }
        public string CellPhone { get; set; }
        public string FaxNumber { get; set; }
        public string Ward { get; set; }
        public bool Resident { get; set; }
        public string UserID { get; set; }
        public Nullable<int> AccessID { get; set; }
        public Nullable<bool> Confirmed { get; set; }
        public string Age { get; set; }
        public string License { get; set; }
    }
}
