//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person_Applications
    {
        public int ApplicationKey { get; set; }
        public int BoardCommissionKey { get; set; }
        public int PersonKey { get; set; }
        public string Supplemental_Answers { get; set; }
        public System.DateTime ApplicationDate { get; set; }
        public Nullable<bool> Accepted { get; set; }
        public Nullable<bool> Appointed { get; set; }
        public Nullable<bool> Expired_Notified { get; set; }
    }
}
