//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voluntary_Survey
    {
        public int Voluntarykey { get; set; }
        public string Source { get; set; }
        public string Source_Details { get; set; }
        public Nullable<bool> Disability { get; set; }
        public string Ethnic_Category { get; set; }
        public string Sex { get; set; }
        public string Age_Category { get; set; }
        public string BoardAppliedFor { get; set; }
        public Nullable<System.DateTime> DateApplied { get; set; }
    }
}
